Updates ApostropheCMS information
mozilla/nunjucks pull request #1347
Opened 2021-03-22 17:01 UTC by abea

## Summary

Proposed change:

This updates the description and quote for ApostropheCMS in the "Who's Using It?" section of the documentation site. Apostrophe is no longer housed within P'unk Avenue and has new URLs.

## Checklist

I've completed the checklist below to ensure I didn't forget anything. This makes reviewing this PR as easy as possible for the maintainers. And it gets this change released as soon as possible.

* [x] Proposed change helps towards [*purpose of this project*](https://github.com/mozilla/nunjucks/blob/master/CONTRIBUTING.md#purpose).
* [x] [*Documentation*](https://github.com/mozilla/nunjucks/tree/master/docs/) is added / updated to describe proposed change.
* [x] [*Tests*](https://github.com/mozilla/nunjucks/tree/master/tests) are added / updated to cover proposed change.
* [x] [*Changelog*](https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md) has an entry for proposed change (if user-facing fix or feature).

2021-03-22 17:01 UTC, abea commented
The updated quote is from @boutell, who is now the CTO for Apostrophe.

2021-03-22 17:05 UTC, boutell commented
Just confirming I agree with this request.

2021-03-23 06:46 UTC, ogonkov requested changes

2021-03-23 06:46 UTC, ogonkov commented on package.json
> +  "version": "3.2.4",
You shouldn't change package version

2021-03-23 15:52 UTC, ogonkov commented
@abea  Changelog changes was OK )

2021-03-23 16:04 UTC, ogonkov approved these changes

2021-12-20 22:22 UTC, abea commented
Hello. Is there any plan to merge this and release @ogonkov ?

2021-12-21 05:07 UTC, ogonkov commented
I dont have permissions im afraid

2022-11-02 21:27 UTC, abea commented
Closing due to inactivity. It is also outdated since ApostropheCMS is on version 3, which also uses Nunjucks. Tagging in @boutell in case the current team wants to resubmit with A3 information.

2022-11-02 21:27 UTC, closed without merging